> 学习来源：[numpy](https://www.numpy.org.cn/user/setting-up.html)

# Numpy
## 简单介绍

### 基本特征
矢量化（Vectorization）和广播（Broadcasting）

### 具体特征
- 多维数组对象 ndarray，拥有数组快速操作的各种API。
- 创建时具有固定的大小，更改 ndarray 大小将会创建一个新数组并删除之前的数组
- 矢量化：代码更简洁，更加 pythonic
- 广播：隐式地逐元素
- 预编译的C代码中“幕后”优化，让 numpy 速度较 python 原生 array 快很多

注意： ndarray 是一个类，拥有许多方法和属性。它的许多方法都是最外层的 NumPy 命名空间中的函数镜像

# numpy 中的属性
numpy 命名空间中的 ndarray 对象也被别名为 array 对象中有下列属性：
- ndarray.ndim - 数组的轴（维度）的个数
- ndarray.shape - 数组的维度。这是一个整数的元组，表示每个维度中数组的大小。对于有 n 行和 m 列的矩阵，shape 是 (n, m)
  shape 的长度就是 ndim
- ndarray.size - 数组元素的总数。等于 shape 的元素的乘积。
- ndarray.dtype - 描述数组中元素类型的对象。可以是 python 自带的，也可以是 numpy 提供的。
- ndarray.itemsize - 数组中每个元素的字节大小。例如，元素为 float64 类型的数组的 itemsize 为8（=64/8），而 complex32 类型
  的数组的 itemsize 为4（=32/8）。它等于 ndarray.dtype.itemsize，可以少一层调用。
- ndarray.data - 该缓冲区包含数组的实际元素。通常不需要使用此属性。

# numpy 数组创建
使用 array 函数从 python 列表或元组中创建数组，注意：
- 不能传入多个数字 作为参数
- array 可以自动转换多维数组
- 可以在创建时显式指定数组的类型，使用 dtype 的参数即可
- 函数 zeros 创建一个由 0 组成的数组
- 函数 ones 创建一个由 1 组成的数组
- 函数 empty 创建一个数组，其初始内容是随机的，取决于内存的状态
- 默认情况下，创建的数组的 dtype 是 float64 类型的。可以根据 dtype 进行指定类型

arange 和 linspace
- arange 类似于 range，有起点终点和步长，其中终点默认**不包含**
- linspace 一般用于浮点数，不在是步长而是指定数组元素个数，其中终点默认**包含**

zeros_like 和 ones_like：接收一个 numpy 数组，生成一个同样 shape 的全 0 或全 1 数组

In [4]:
import numpy as np

a = np.array([(1.5,2,3), (4,5,6)])
print(a)

b = np.zeros( (3,4) )
print(b)

c = np.ones( (2,3,4), dtype=np.int16 )
print(c)

d = np.empty( (2,3) )
print(d)

e = np.arange( 10, 30, 5 )
print(e)

f = np.linspace( 0, 2, 9 )
print(f)


[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]
[10 15 20 25]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


# numpy 的打印

- 最后一个轴(axis最大的)从左到右打印，
- 倒数第二个从上到下打印，
- 其余部分也从上到下打印，每个切片用空行分隔。

所以一般在二维数组中，可以理解为打印的结果可以使用正规二维矩阵的行列来寻址

In [5]:
a = np.arange(6).reshape(2, 3)
print(a)

[[0 1 2]
 [3 4 5]]


# numpy 的基本操作
几乎所有的算数运算符在 numpy 中都会应用到逐个元素级别
- `*` 运算符用于逐元素的乘法操作，类似于内积。`@` 运算符才是矩阵乘法。
- `+=` 和 `*=` 会更直接更改被操作的 array 而不会创建新 array。
- 类型向上转换，无法 auto 地向下转换

In [6]:
A = np.array( [[1,1],
              [0,1]] )
B = np.array( [[2,0],
              [3,4]] )

print(A * B)
print(A @ B)
print(B.dtype)

C = np.exp(B*1j)
print(C)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
int32
[[-0.41614684+0.90929743j  1.        +0.j        ]
 [-0.9899925 +0.14112001j -0.65364362-0.7568025j ]]


# numpy 指定具体轴
`axis=0` 一般代表最外的轴，其次是 `axis=1`。
在二维矩阵中 `axis=0` 代表操作每一个 column；`axis=1` 代表操作每一个 row

In [15]:
a = np.arange(12).reshape(3,4)
print(a)
print(a.sum(axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]


# numpy 的索引、切片和迭代
类似列表

反转一维矩阵：a_rev = a[::-1]

三个点（ ... ）表示产生完整索引元组所需的冒号

如果想要对数组中的每个元素执行操作，可以使用flat属性，该属性是数组的所有元素的迭代器

In [16]:
a = np.arange(10)**2
print(a)
a[:6:2] = -1000 
print(a)
b = a[::-1]
print(b)

[ 0  1  4  9 16 25 36 49 64 81]
[-1000     1 -1000     9 -1000    25    36    49    64    81]
[   81    64    49    36    25 -1000     9 -1000     1 -1000]


In [17]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                 [ 10, 12, 13]],
                [[100,101,102],
                 [110,112,113]]])
print(c[1, ...])

[[100 101 102]
 [110 112 113]]


In [18]:
b = np.arange(12).reshape(3,4)
print(b)

for row in b:
    print(row)

for elem in b.flat:
    print(elem)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
0
1
2
3
4
5
6
7
8
9
10
11


# numpy 广播规则
广播允许 通用功能 以有意义的方式处理 **不具有完全相同形状** 的输入。
规则：
- 所有输入数组不具有相同数量的维度，则将“1”重复地预先添加到较小数组的形状，直到所有数组具有相同数量的维度。
- 确保沿特定维度的大小为1的数组表现为具有沿该维度具有 最大形状的数组 的大小。