# pytorch 基础

Pytorch 由 Facebook 人工智能研究院于 2017 年推出，具有强大的 GPU 加速张量计算功能，并且能够自动进行微分计算，从而可以使用基于梯度的方法对模型参数进行优化

## pytorch lib function and object

### tensor

张量 (Tensor) 是深度学习的基础。
- 0 维张量称为标量 (scalar)
- 1 维张量称为向量 (vector)
- 2 维张量称为矩阵 (matrix)

Pytorch 本质上就是一个基于张量的数学计算工具包

In [2]:
import torch
t1 = torch.empty(2, 3)
t2 = torch.rand(2, 3) # each value taken from [0, 1)
t3 = torch.randn(2, 3) # each value taken from a normal distribution
t4 = torch.zeros(2, 3) # all zeros
t5 = torch.arange(0, 10, 2) # start, end, step
print(t5)

tensor([0, 2, 4, 6, 8])


In [3]:
# 也可以通过 torch.tensor() 或者 torch.from_numpy() 基于已有的数组或 Numpy 数组创建张量
import numpy as np
arr = np.array([1, 2, 3])
t6 = torch.tensor(arr)

In [4]:
"""
上面这些方式创建的张量会存储在内存中并使用 CPU 进行计算，如果想要调用 GPU 计算，需要直接在 GPU 中创建张量或者将张量送入到 GPU 中，一共有三种方法
"""
# 方法一：直接在 GPU 中创建张量
device = torch.device('cuda')
t7 = torch.rand(2, 3, device=device)

# 方法二：将张量送入到 GPU 中
t8 = torch.rand(2, 3)
t8 = t8.to(device)

# 方法三：之间调用 cuda 函数
t9 = torch.rand(2, 3)
t9 = t9.cuda()

# 方法一和方法三都不够好，因为如果没有 GPU，程序会报错，所以推荐使用方法二

### tensor computation

类似 numpy 的 broadcasting。

基本运算：加减乘除、三角函数、向量点积、矩阵相乘

In [6]:
t10 = torch.randn(2, 3)
t11 = torch.randn(2, 3)
# print(t10.dot(t11)) # error
print(t10[0].dot(t11[0]))
t12 = torch.randn(3, 2)
print(t10.mm(t12))

tensor(0.6236)
tensor([[ 6.4440e-01, -9.9170e-01],
        [ 1.9814e-04,  1.4675e+00]])


In [7]:
"""
一个显著的特点就是 pytorch 在 gpu 上的运算会比 cpu 快很多。
另外 pytorch 可以在 gpu 上原生运行，而 numpy 却只能在 cpu 上运行。
"""
import timeit

M = torch.rand(1000, 1000)
print(timeit.timeit(lambda: M.mm(M).mm(M), number=5000))

N = torch.rand(1000, 1000).cuda()
print(timeit.timeit(lambda: N.mm(N).mm(N), number=5000))

40.77812500000073
7.684117200000401


### automatic differentiation

Pytorch 提供自动计算梯度的功能，可以自动计算一个函数关于一个变量在某一取值下的导数，从而基于梯度对参数进行优化，这就是机器学习中的训练过程。

In [8]:
x = torch.tensor([2.], requires_grad=True)
y = torch.tensor([3.], requires_grad=True)
z = (x + y) * (y - 2)
print(z)
z.backward()
print(x.grad, y.grad)

tensor([5.], grad_fn=<MulBackward0>)
tensor([1.]) tensor([6.])


### modify tensor shape

Pytorch 共提供了 4 种调整张量形状的函数

#### view

#### reshape

#### transpose

#### permute

## dataloader

## train model

## save and load model